version: '3.9'

services:
  php:
    build: .
    container_name: fiserv-test-php
    volumes:
      - ./:/var/www
    networks:
      - fiserv-test-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - fiserv-test-network

  mysql:
    image: mysql:8.0
    container_name: fiserv-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: fiserv
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fiserv-test-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - fiserv-test-network

networks:
  fiserv-test-network:
    driver: bridge

volumes:
  mysql-data: